### ISSUE TITLE
linux环境下总是报NoClassDefFoundError

### ISSUE THREAD

**Issue by Houtx** [jamesluozhiwei/seetafaceJNI#14]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.lzw.face.FaceHelper

之前调整好了一次，过了一段时间又不行了（中间服务器被重启过）

**Comment by Houtx** [comment]
![8RUG}A$KB99QGFUHQ8 JFGJ](https://user-images.githubusercontent.com/17922172/192418833-1af8ad96-1b92-4e76-a241-9e2b25d252cc.png)

**Comment by Houtx** [comment]
@jamesluozhiwei

**Comment by jamesluozhiwei** [comment]
> @jamesluozhiwei

JAVA重启后 无法重复加载动态库 请参考该文章(https://blog.csdn.net/lovesummerforever/article/details/25826993)解决方案

**Comment by Houtx** [comment]
> 

没采用此解决方法，经过尝试，升级gcc版本解决。
