### ISSUE TITLE
链接访问不了

### ISSUE THREAD

**Issue by Vector6662** [jamesluozhiwei/seetafaceJNI#6]
https://my.oschina.net/u/1580184/blog/3042404 访问失败，似乎文章已经删除

**Comment by jamesluozhiwei** [comment]
> https://my.oschina.net/u/1580184/blog/3042404 访问失败，似乎文章已经删除

可以访问 可能是你网络问题

**Comment by only404** [comment]
https://pan.baidu.com/s/1HJj8PEnv3SOu6ZxVpAHPXg   大佬  下载不了了，可以从新发一下嘛

**Comment by jamesluozhiwei** [comment]
> https://pan.baidu.com/s/1HJj8PEnv3SOu6ZxVpAHPXg 大佬 下载不了了，可以从新发一下嘛

hi，这是我用百度网盘分享的内容~复制这段内容打开「百度网盘」APP即可获取 链接:https://pan.baidu.com/s/193AecRyV8yY5Plkb623Kmw 提取码:thg1
